# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='username_id'),
        ),
    ]
