# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username2',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
