# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170206_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookprofile',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
