# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_myuser_username2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
