# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-15 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_facebookprofile_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookprofile',
            name='gender',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
