# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20170213_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(default='N', max_length=1)),
                ('webpull', models.CharField(max_length=1000, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('times_called', models.PositiveIntegerField(default=0)),
                ('level', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='modtestmod',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='username2',
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='surname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='username_id',
            field=models.PositiveIntegerField(default=2, primary_key=True, serialize=False, verbose_name='username_id'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ModtestMod',
        ),
        migrations.AddField(
            model_name='facebookprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
