# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170213_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookprofile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'managed': True},
        ),
    ]
